easy_admin:
    entities:
        Traobject:
            class: App\Entity\Traobject
            label: 'Traobject'
            list:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
                    - { property: 'event_at', type: 'datetime' }
                    - { property: 'city', type: 'text' }
                    - { property: 'county', type: 'text' }
            show:
                fields:
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
        User:
            class: App\Entity\User
            label: 'User'
            list:
                fields:
                    - { property: 'lastname', type: 'text' }
                    - { property: 'firstname', type: 'text' }
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
                    - { property: 'email', type: 'email' }
                    - { property: 'password', type: 'password' }
                    - { property: 'roles' }
        Category:
            class: App\Entity\Category
            label: 'User'
            list:
                fields:
                    - { property: 'label', type: 'text' }
                    - { property: 'icon', type: 'text' }
                    - { property: 'color', type: 'text' }
