easy_admin:
    entities:
        Traobject:
            class: App\Entity\Traobject
            label: 'Traobject'
            list:
                fields:
                    - { property: 'title', type: 'text', label: 'Titre' }
                    - { property: 'picture', type: 'image',label: 'Photo', base_path: '%app.path.uploads_dir%' }
                    - { property: 'event_at', type: 'datetime', label: 'Date' }
                    - { property: 'city', type: 'text', label: 'Ville' }
                    - { property: 'county', type: 'text', label: 'Département' }
            show:
                fields:
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
        User:
            class: App\Entity\User
            label: 'Utilisateur'
            list:
                fields:
                    - { property: 'lastname', type: 'text', label: 'Nom' }
                    - { property: 'firstname', type: 'text', label: 'Prénom' }
                    - { property: 'picture', type: 'image', label: 'Photo', base_path: '%app.path.uploads_dir%' }
                    - { property: 'email', type: 'email', label: 'Email' }
                    - { property: 'password', type: 'password', label: 'Mot de passe' }
                    - { property: 'roles', label: 'Role' }
        Category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
                fields:
                    - { property: 'label', type: 'text', label: 'Catégorie' }
                    - { property: 'icon', type: 'text', label: 'Icone' }
                    - { property: 'color', type: 'text', label: 'Couleur' }
            show:
                fields:
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
        County:
            class: App\Entity\County
            label: 'Départements'
            list:
                fields:
                    - { property: 'label', type: 'text', label: 'Département' }
                    - { property: 'zipcode', type: 'text', label: 'Code postal' }
        Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            list:
                fields:
                    - { property: 'content', type: 'text', label: 'Contenu' }
                    - { property: 'created_at', type: 'text', label: 'Date' }
