easy_admin:
    entities:
        Traobject:
            class: App\Entity\Traobject
            label: 'Traobject'
            list:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
                    - { property: 'event_at', type: 'datetime' }
                    - { property: 'city', type: 'text' }
                    - { property: 'county', type: 'text' }
            show:
                fields:
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
        User:
            class: App\Entity\User
            label: 'Utilisateur'
            list:
                fields:
                    - { property: 'lastname', type: 'text' }
                    - { property: 'firstname', type: 'text' }
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
                    - { property: 'email', type: 'email' }
                    - { property: 'password', type: 'password' }
                    - { property: 'roles' }
        Category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
                fields:
                    - { property: 'label', type: 'text' }
                    - { property: 'icon', type: 'text' }
                    - { property: 'color', type: 'text' }
            show:
                fields:
                    - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
        County:
            class: App\Entity\County
            label: 'Départements'
            list:
                fields:
                    - { property: 'label', type: 'text' }
                    - { property: 'zipcode', type: 'text' }
        Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            list:
                fields:
                    - { property: 'content', type: 'text' }
                    - { property: 'created_at', type: 'text' }
