vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.product_images%'
